repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
    exclude: '.*/Baseline'
  - id: end-of-file-fixer
    exclude: '.*/Baseline'
  - id: check-yaml
  - id: check-added-large-files
