repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
    exclude: '.*/Baseline'
  - id: end-of-file-fixer
    exclude: '.*/Baseline'
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
  - id: stray_baselines
    name: Check for stray BTest baselines
    entry: ./tests/scripts/stray_baselines.py
    language: python
    pass_filenames: false
