name: Test & install with Zeek nightly build

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-nightly:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # We need the git tags in order to install the latest
          # one, as zkg would do if using a package source:
          fetch-depth: 0
      - uses: zeek/action-zkg-install@v1
        with:
          zeek_version: 'zeek-nightly'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: zkg-logs
          path: ${{ github.workspace }}/.action-zkg-install/artifacts
